### ISSUE TITLE
Latent State Estimates

### ISSUE THREAD

**Issue by syed911** [mattjj/pylds#11]
Thank you for this wonderful package. I would like ask how I can output the latent state estimates. Thanks.

**Comment by mattjj** [comment]
Glad you like it! Though it's a bit thin on documentation, so this is probably a good issue to answer in case anyone else has the same question.

It depends on what kind of estimate you want. The most straightforward would be to get the expected states given fixed parameters and observations (or, equivalently, the MAP estimate of the states with fixed parameters and observations). Those are output by the E-step of the EM algorithm, so here are two ways you might get them:

In the [EM example file](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/examples/EM.py), you can take the [LDS model instance](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/examples/EM.py#L24) and call `model.smooth(data)`. (You could also grab the expected states that have already been calculated during the EM algorithm for the data that was added to the model by getting the member `model.states_list[0].gaussian_states`.)

If you want to avoid the object-oriented interface, you can just call the `E_step` or `info_E_step` functions directly; see the [states.py file](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/pylds/states.py) for examples. Those are mostly implemented in [lds_messages.pyx](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/pylds/lds_messages.pyx#L183) and [lds_info_messages.pyx](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/pylds/lds_info_messages.pyx#L71), though they are wrapped in [lds_messages_interface.py](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/pylds/lds_messages_interface.py) just to normalize the input arrays (ensuring they have the right layout, right number of dimensions, right dtypes, etc.).

There are other kinds of state estimates you might want. For example, maybe you want to be a Bayesian and marginalize out all the parameters; in that case, you might want to run a Gibbs sampler over the states and parameters, collect samples of the states from the MCMC trajectory, and then form some estimator based on those collected samples. This package lets you do that, and the above hints along with the [gibbs.py example file](https://github.com/mattjj/pylds/blob/32491cbe0f5672f300db6dd9fba7b046791b01d7/examples/gibbs.py) should give you an idea of how to do it!
