### ISSUE TITLE
Strange behavior of sample_predictions

### ISSUE THREAD

**Issue by hedgy123** [mattjj/pylds#12]
Hi Matt and Scott,

   Thanks for adding the exogenous input capability to the code!  Very cool!

   I am testing it right now with a bunch of sample data, and I am getting some strange results for sample_predictions regardless of the specifics of the LDS model or sampling.  Here are the data:

      inputs = array([[ 0.        ,  0.        ],
        [ 2.72785283,  7.53608657],
        [ 0.        ,  7.23201033],
        [ 2.0261219 ,  7.07866193],
        [ 2.42989525,  7.67644583],
        [ 2.80870737,  7.83475645],
        [ 0.        ,  7.9209767 ],
        [ 0.        ,  7.79186987],
        [ 2.78714571,  8.37162161],
        [ 2.49732917,  8.14119562],
        [ 2.71444   ,  7.94740989],
        [ 2.54583288,  8.05844122],
        [ 2.51490101,  8.18854467],
        [ 1.61097519,  7.88220925],
        [ 2.58138165,  7.85400085],
        [ 2.45695553,  7.71646971],
        [ 2.86483477,  7.96989029]])
  

      Data = array([[ 7.53608657],
        [ 7.23201033],
        [ 7.07866193],
        [ 7.67644583],
        [ 7.83475645],
        [ 7.9209767 ],
        [ 7.79186987],
        [ 8.37162161],
        [ 8.14119562],
        [ 7.94740989],
        [ 8.05844122],
        [ 8.18854467],
        [ 7.88220925],
        [ 7.85400085],
        [ 7.71646971],
        [ 7.96989029],
        [ 7.68803383]])

Just to be specific, consider 

     model = DefaultLDS(D_obs = 1, D_latent = 2, D_input = 2)

Prediction step:

     T_given = 13
     T_predict = 4
     given_data= data[:T_given]
     given_inputs = inputs[:T_given]

     preds = \
         model.sample_predictions(
             given_data, inputs=given_inputs,
             Tpred=T_predict,
             inputs_pred=inputs[T_given:T_given + T_predict])

And here's the plot:

[figure_2.pdf](https://github.com/mattjj/pylds/files/687825/figure_2.pdf)

What I don't get is why even the first predicted point is so far off the real data.  Isn't it anchored to the real deal?  Or am I using sample_predictions wrong?

**Comment by slinderman** [comment]
Hi @hedgy123,
Thanks for raising this! There was definitely a minor bug in `sample_predictions`, and I just fixed it in https://github.com/mattjj/pylds/commit/6a05fdce508f6251a461ab435387acfb31b442ce. 

However, I reran your example and I think the jump is partly explained by uncertainty in the latent state. I wrote a simple gist to play with this, and when I plot the smoothed data along with the sampled predictions, the jump doesn't seem so strange. 

https://gist.github.com/slinderman/31fdf5acdc0affdf4dc60670069d314a

Please let us know if you think this solves your issue.

Best,
Scott

**Comment by hedgy123** [comment]
Thanks so much, Scott!  The fix definitely helped.

I think it might also help if I were to place some ad-hoc constraints on the parameters.  For example, suppose it's known empirically that specific inputs should result in non-decreasing outcomes (in other words, the regression coefficients for a given input should always be >=0).  Is there any way to impose these types of constraints on the model?

Thank you again, I really appreciate your help.

**Comment by slinderman** [comment]
Hi @hedgy123, sorry to let this issue slide.  To add constraints on the regression, you'd have to write a special subclass of `Regression`.  I imagine this is more work than it's worth, but let me know if you give it a shot!
