### ISSUE TITLE
installation issue: No module named future.moves.urllib.request

### ISSUE THREAD

**Issue by mnouri62** [mattjj/pylds#13]
hi, I'm trying to install from a git clone and see the following errors:

C:\Anaconda1>cd
C:\Anaconda1
C:\Anaconda1>cd pylds
C:\Anaconda1\pylds>pip install pylds
Collecting pylds
  Using cached pylds-0.0.4.tar.gz
Collecting numpy>=1.9.3 (from pylds)
  Using cached numpy-1.12.1-cp27-none-win_amd64.whl
Collecting scipy>=0.16 (from pylds)
  Using cached scipy-0.19.0.zip
Requirement already satisfied: matplotlib in c:\anaconda1\lib\site-packages (fro
m pylds)
Collecting pybasicbayes (from pylds)
  Using cached pybasicbayes-0.2.2.tar.gz
Collecting pypolyagamma>=1.1 (from pylds)
  Using cached pypolyagamma-1.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mn_work\appdata\local\temp\pip-build-luoy1p\pypolyagamma\se
tup.py", line 7, in <module>
        from future.moves.urllib.request import urlretrieve
    ImportError: No module named future.moves.urllib.request

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mn_work\
appdata\local\temp\pip-build-luoy1p\pypolyagamma\

C:\Anaconda1\pylds>

**Comment by mattjj** [comment]
It looks like pypolyagamma's setup.py has an unlisted dependence on the future module. You should be able to install it with `pip install future`, and then your installation of pypolyagamma (and ultimately pylds) should go through.

**Comment by slinderman** [comment]
thanks for the heads up; i'll add this to pypolyagamma

**Comment by mattjj** [comment]
@slinderman rolled in a fix to pypolyagamma, so I'm going to close this issue. Please reopen if necessary!

**Comment by mnouri62** [comment]
thanks, there is still issues with installing pypolyagamma which has to do with a conflict with microsoft visual studio (I submitted the problem to pypolyagamma's issue page) so I couldn't install either that or pylds

**Comment by slinderman** [comment]
I opened a new issue to deal with this: https://github.com/mattjj/pylds/issues/14.  Short story: we should remove the pypolyagamma dependency.
