### ISSUE TITLE
Installation issue on windows: "pylds\lds_info_messages.c: No such file or directory"

### ISSUE THREAD

**Issue by veronica320** [mattjj/pylds#21]
Hi, thanks for your work!
I have an issue installing this package on windows, and the error message is as follows:

`c1: fatal error C1083: can't open source file: “pylds\lds_info_messages.c”: No such file or directory`

Would you kindly give a hint on what might be going wrong? Thanks a lot!

**Comment by slinderman** [comment]
Hi, 

PyLDS uses Cython to translate the *.pyx files into c and then compile them.  On Windows, please try using Anaconda to install gcc (`conda install gcc`) and then install pylds from source via `python setup.py install` (or something similar).

Best,
Scott

**Comment by veronica320** [comment]
Problem resolved. Thank you!
