### ISSUE TITLE
add control inputs

### ISSUE THREAD

**Issue by mattjj** [mattjj/pylds#3]
You know, CRF node potentials! Like u[t].

**Comment by slinderman** [comment]
Bumping this since we continue to get requests for this feature.  Here's a bit more info from Murphy pgs 641--644.  Let 
```
z_t ~ N(A_t z_{t-1} + B_t u_t, Q_t)
x_t ~ N(C_t z_t + D_t u_t, R_t)
```
Inputs factor into the prediction step,
```
\mu_{t|t-1} = A_t \mu_{t-1} + B_t u_t
```
and into the measurement (condition) step,
```
\hat{y}_t = C_t \mu_{t|t-1} + D_t u_t
```
Corresponding changes to the info form shouldn't be hard to derive.

**Comment by mattjj** [comment]
Yeah! So for message passing in distribution form, clearly we just need to adjust some means. In particular, as you said, [`predict`](https://github.com/mattjj/pylds/blob/73fceec2215347e0a0e35a5f116e69aa719b2efc/pylds/lds_messages.pyx#L431) needs to learn how to add B_t u_t by using a `dcopy` or `dgemv` into `mu_predict` before the `dgemv` and [`condition_on`](https://github.com/mattjj/pylds/blob/73fceec2215347e0a0e35a5f116e69aa719b2efc/pylds/lds_messages.pyx#L392) needs to replace y_t with y_t - D_t u_t by using a `daxpy` instead of `dcopy`.

For information form, this seems like a good place to write out some notes. We want to write out the joint distribution as a product of local directed factors, suppressing conditioning on parameters,

![image](https://cloud.githubusercontent.com/assets/1458824/14763939/12f4d248-0974-11e6-9ae0-0be12275f3d7.png)

and write those local terms as pair and node potentials on the state sequence x,

![image](https://cloud.githubusercontent.com/assets/1458824/14764076/8b9ae42c-0978-11e6-8038-f5cbe7a44d7d.png)

where I've dropped some base density terms involving \pi and also dropped time indices for parameters on the last line of each equation.

The only really new thing there is the linear term on the pairwise log potential; previously it was just a quadratic form in x_t. The node potential has the same form as before, just with y_t replaced with y_t - D_t u_t, as expected. So in the information form message passing code we need to add linear terms in the pairwise potentials, since with my lack of foresight I [assumed there would only be J_pair's and no h_pair's for the pairwise potentials](https://github.com/mattjj/pylds/blob/73fceec2215347e0a0e35a5f116e69aa719b2efc/pylds/lds_info_messages.pyx#L29). The change to the node potentials would happen in Python, [where we set up J_node and h_node](https://github.com/mattjj/pylds/blob/73fceec2215347e0a0e35a5f116e69aa719b2efc/pylds/states.py#L158), and we just need to replace `data` with `data - np.einsum('tj,tij->ti', control_inputs, self.D)` there.

Disclaimer: those formulas need to be checked and the variables may not correspond precisely to the variable names in the code (e.g. sign errors may be present).

**Comment by mattjj** [comment]
For documentation purposes, the other pieces to the puzzle are the formulas for conditioning and marginalizing in information form, plus the RTS smoother logic. Those are currently best represented in the SVAE repo: [conditioning and marginalizing](https://github.com/mattjj/svae/blob/a89e886acf9c8f4afaf0b19b8debe102a3b153c1/svae/lds/gaussian.py#L41-70) and [RTS update](https://github.com/mattjj/svae/blob/a89e886acf9c8f4afaf0b19b8debe102a3b153c1/svae/lds/gaussian.py#L91-110).

**Comment by slinderman** [comment]
This has been incorporated into master with https://github.com/mattjj/pylds/pull/6

See `notes/info_form.tex` for more detailed derivations.
